comment "Exported from Arsenal by Nichols";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "PLA_CombatUniform_SBCB";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_packingBandage";};
_this addItemToUniform "ACE_MapTools";
_this addItemToUniform "ACE_Flashlight_KSF1";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_EarPlugs";};
_this addItemToUniform "vme_camonet_FOR";
_this addVest "PLA_T15Vest_RF";
for "_i" from 1 to 2 do {_this addItemToVest "ACE_morphine";};
for "_i" from 1 to 2 do {_this addItemToVest "ACE_fieldDressing";};
_this addItemToVest "ACE_IR_Strobe_Item";
for "_i" from 1 to 2 do {_this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {_this addItemToVest "SmokeShell";};
_this addItemToVest "SmokeShellRed";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellYellow";
for "_i" from 1 to 6 do {_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10";};
_this addItemToVest "Chemlight_blue";
_this addItemToVest "ACE_Chemlight_HiRed";
_this addItemToVest "ACE_Chemlight_IR";
_this addItemToVest "Chemlight_red";
for "_i" from 1 to 3 do {_this addItemToVest "VME_QSZ92_20Rnd_DAP92";};
_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10_Tracer_Green";
_this addBackpack "PLA_UAV_backpack";
_this addHeadgear "VME_PLA_Helmet_R_O";
_this addGoggles "PLA_goggle";

comment "Add weapons";
_this addWeapon "vme_pla_qbz95B_1";
_this addPrimaryWeaponItem "VME_QBZ95_flashlight_laser";
_this addPrimaryWeaponItem "VME_Eotech553";
_this addPrimaryWeaponItem "VME_rail_scopes";
_this addWeapon "vme_pla_qsz92";
_this addWeapon "Binocular";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "TFAR_anprc148jem";
_this linkItem "PLA_UavTerminal";
_this linkItem "NVGoggles_OPFOR";

comment "Set identity";
_this setFace "AsianHead_A3_06";
_this setSpeaker "male03chi";
