comment "Exported from Arsenal by Nichols";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "PLA_CombatUniform_SBCB";
_this addItemToUniform "acc_flashlight";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_packingBandage";};
_this addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_Flashlight_KSF1";};
_this addItemToUniform "ACE_IR_Strobe_Item";
_this addItemToUniform "Chemlight_yellow";
_this addItemToUniform "Chemlight_red";
_this addVest "PLA_T15Vest_RF";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellRed";
for "_i" from 1 to 2 do {_this addItemToVest "HandGrenade";};
for "_i" from 1 to 5 do {_this addItemToVest "1Rnd_HE_Grenade_shell";};
_this addItemToVest "1Rnd_Smoke_Grenade_shell";
_this addItemToVest "1Rnd_SmokeRed_Grenade_shell";
_this addItemToVest "1Rnd_SmokeGreen_Grenade_shell";
_this addItemToVest "1Rnd_SmokeYellow_Grenade_shell";
_this addItemToVest "1Rnd_SmokePurple_Grenade_shell";
for "_i" from 1 to 6 do {_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10";};
_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10_Tracer_Green";
for "_i" from 1 to 2 do {_this addItemToVest "VME_QSZ92_20Rnd_DAP92";};
_this addBackpack "PLA_AssaultPack2_Base";
_this addItemToBackpack "ACE_EntrenchingTool";
_this addItemToBackpack "ACE_wirecutter";
for "_i" from 1 to 20 do {_this addItemToBackpack "VME_1Rnd_HE_GL";};
for "_i" from 1 to 10 do {_this addItemToBackpack "VME_1Rnd_Smoke_GL";};
_this addHeadgear "VME_PLA_Helmet_R_O";
_this addGoggles "PLA_goggle";

comment "Add weapons";
_this addWeapon "vme_pla_qbz95_1GL";
_this addPrimaryWeaponItem "VME_QBZ95_flashlight";
_this addPrimaryWeaponItem "VME_Eotech_557_Magnifier_DOWN";
_this addPrimaryWeaponItem "VME_rail_scopes";
_this addWeapon "vme_pla_qsz92";
_this addWeapon "Binocular";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "TFAR_anprc148jem";
_this linkItem "ItemGPS";
_this linkItem "NVGoggles_OPFOR";

comment "Set identity";
_this setFace "AsianHead_A3_05";
_this setSpeaker "male03chi";
