comment "Exported from Arsenal by Nichols";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "PLA_CombatUniform_SWCB";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_packingBandage";};
_this addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_epinephrine";};
_this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_quikclot";};
_this addItemToUniform "SmokeShell";
_this addItemToUniform "Laserbatteries";
_this addVest "PLA_T15Vest_RD";
_this addItemToVest "ACE_IR_Strobe_Item";
for "_i" from 1 to 6 do {_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10";};
for "_i" from 1 to 2 do {_this addItemToVest "VME_QBZ95_1_30Rnd_DBP10_Tracer_Green";};
for "_i" from 1 to 2 do {_this addItemToVest "SmokeShell";};
_this addItemToVest "SmokeShellRed";
_this addItemToVest "SmokeShellPurple";
_this addItemToVest "SmokeShellOrange";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellBlue";
_this addItemToVest "ACE_HandFlare_Yellow";
_this addItemToVest "ACE_HandFlare_White";
_this addItemToVest "ACE_Chemlight_HiYellow";
_this addItemToVest "ACE_Chemlight_HiWhite";
_this addItemToVest "ACE_Chemlight_HiRed";
_this addItemToVest "ACE_Chemlight_HiOrange";
_this addItemToVest "ACE_Chemlight_IR";
_this addItemToVest "ACE_Chemlight_Orange";
_this addHeadgear "VME_PLA_Helmet_R_O";
_this addGoggles "PLA_goggle";

comment "Add weapons";
_this addWeapon "vme_pla_qbz95_1";
_this addPrimaryWeaponItem "VME_QBZ95_flashlight_laser";
_this addPrimaryWeaponItem "VME_95_1_PST";
_this addPrimaryWeaponItem "VME_rail_scopes";
_this addWeapon "vme_pla_qsz92";
_this addWeapon "Laserdesignator_02";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "TFAR_anprc148jem";
_this linkItem "ItemGPS";
_this linkItem "NVGoggles_OPFOR";

comment "Set identity";
_this setFace "AsianHead_A3_05";
_this setSpeaker "male02chi";